name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: terraform
  cancel-in-progress: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Remove Terraform lock
    - name: Remove Terraform lock
      run: |
        az storage blob delete --container-name tfstate \
          --name infra.tfstate.lock \
          --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} || true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Terraform Backend Setup
    - name: Create Terraform Backend Resources
      run: |
        echo "Creating RG if not exists..."
        az group create --name tfstate-rg --location westeurope

        echo "Creating Storage Account if not exists..."
        az storage account create \
          --name mfreiretfstatestorage \
          --resource-group tfstate-rg \
          --location westeurope \
          --sku Standard_LRS || true

        echo "Retrieving Storage Account Key..."
        ACCOUNT_KEY=$(az storage account keys list \
          --resource-group tfstate-rg \
          --account-name mfreiretfstatestorage \
          --query "[0].value" -o tsv)

        echo "Creating container if not exists..."
        az storage container create \
          --name tfstate \
          --account-name mfreiretfstatestorage \
          --account-key "$ACCOUNT_KEY" || true

        echo "Done creating backend."

    - name: Terraform Init
      working-directory: terraform
      run: |
        terraform init \
          -backend-config="resource_group_name=tfstate-rg" \
          -backend-config="storage_account_name=mfreiretfstatestorage" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=infra.tfstate"

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -var "suffix=prod" -var "greeting_name=Mario"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: terraform
      run: terraform apply -auto-approve -var="suffix=prod" -var="greeting_name=Mario"

    # Deploy PHP App
    - name: Deploy PHP
      uses: azure/webapps-deploy@v2
      with:
        app-name: hello-web-prod
        package: ./app/.